from codeable_models import CClass, CBundle, add_links, CStereotype, CMetaclass, CEnum, CAttribute 
from metamodels.microservice_dfds_metamodel import * 
from plant_uml_renderer import PlantUMLGenerator 
plantuml_path = "../../plantuml.jar" 
output_directory = "." 
model_name = "piggymetrics_fd5ee3c"
statistics_service = CClass(service, "statistics-service", stereotype_instances = [pre_authorized_endpoints, local_logging, resource_server, internal], tagged_values = {'Port': 7000, 'Endpoints': "['/{accountName}', '/latest', '/current']", 'Pre-authorized Endpoints': "['/{accountName}']"})
turbine_stream_service = CClass(service, "turbine-stream-service", stereotype_instances = [monitoring_server, infrastructural], tagged_values = {'Port': 8989, 'Monitoring Server': 'Turbine'})
account_service = CClass(service, "account-service", stereotype_instances = [resource_server, circuit_breaker, pre_authorized_endpoints, local_logging, internal], tagged_values = {'Endpoints': "['/{name}', '/', '/current', '/statistics/{accountName}', '/uaa/users']", 'Pre-authorized Endpoints': "['/{name}']", 'Circuit Breaker': 'Hystrix', 'Port': 6000})
notification_service = CClass(service, "notification-service", stereotype_instances = [local_logging, resource_server, internal], tagged_values = {'Endpoints': "['/recipients', '/recipients/current', '/accounts/{accountName}']", 'Port': 8000})
gateway = CClass(service, "gateway", stereotype_instances = [gateway, load_balancer, infrastructural], tagged_values = {'Load Balancer': 'Ribbon', 'Port': 4000, 'Gateway': 'Zuul'})
auth_service = CClass(service, "auth-service", stereotype_instances = [csrf_disabled, resource_server, infrastructural, token_server, pre_authorized_endpoints, local_logging, authentication_scope_all_requests, authorization_server, encryption], tagged_values = {'Endpoints': "['/users', '/users/current']", 'Port': 5000, 'Authorization Server': 'Spring OAuth2'})
monitoring = CClass(service, "monitoring", stereotype_instances = [monitoring_dashboard, infrastructural], tagged_values = {'Port': 8080, 'Monitoring Dashboard': 'Hystrix'})
registry = CClass(service, "registry", stereotype_instances = [service_discovery, infrastructural], tagged_values = {'Service Discovery': 'Eureka', 'Port': 8761})
config = CClass(service, "config", stereotype_instances = [basic_authentication, configuration_server, infrastructural, csrf_disabled], tagged_values = {'Port': 8888, 'Configuration Server': 'Spring Cloud Config'})
account_mongodb = CClass(service, "account-mongodb", stereotype_instances = [plaintext_credentials, database], tagged_values = {'Password': 'password\n', 'Username': 'user'})
notification_mongodb = CClass(service, "notification-mongodb", stereotype_instances = [plaintext_credentials, database], tagged_values = {'Password': 'password\n', 'Username': 'user'})
auth_mongodb = CClass(service, "auth-mongodb", stereotype_instances = [plaintext_credentials, database], tagged_values = {'Password': 'password\n', 'Username': 'user'})
statistics_mongodb = CClass(service, "statistics-mongodb", stereotype_instances = [plaintext_credentials, database], tagged_values = {'Password': 'password\n', 'Username': 'user'})
rabbitmq = CClass(service, "rabbitmq", stereotype_instances = [message_broker, infrastructural], tagged_values = {'Port': 15672, 'Message Broker': 'RabbitMQ'})
user = CClass(external_component, "user", stereotype_instances = [user_stereotype, entrypoint, exitpoint])
external_website = CClass(external_component, "external-website", stereotype_instances = [entrypoint, exitpoint, external_website], tagged_values = {'URL': 'https://api.exchangeratesapi.io'})
mail_server = CClass(external_component, "mail-server", stereotype_instances = [plaintext_credentials, mail_server, entrypoint, exitpoint], tagged_values = {'Host': 'smtp.gmail.com', 'Password': 'dev-password', 'Username': 'dev-user'})
add_links({config: statistics_service}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: turbine_stream_service}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: account_service}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: notification_service}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: gateway}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: auth_service}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: monitoring}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({config: registry}, stereotype_instances = [plaintext_credentials_link, restful_http])
add_links({statistics_mongodb: statistics_service}, stereotype_instances = [plaintext_credentials_link, jdbc], tagged_values = {'Password': 'password', 'Username': 'user'})
add_links({account_mongodb: account_service}, stereotype_instances = [plaintext_credentials_link, jdbc], tagged_values = {'Password': 'password', 'Username': 'user'})
add_links({notification_mongodb: notification_service}, stereotype_instances = [plaintext_credentials_link, jdbc], tagged_values = {'Password': 'password', 'Username': 'user'})
add_links({auth_mongodb: auth_service}, stereotype_instances = [plaintext_credentials_link, jdbc], tagged_values = {'Password': 'password', 'Username': 'user'})
add_links({auth_service: registry}, stereotype_instances = [restful_http])
add_links({notification_service: registry}, stereotype_instances = [restful_http])
add_links({turbine_stream_service: registry}, stereotype_instances = [restful_http])
add_links({statistics_service: registry}, stereotype_instances = [restful_http])
add_links({account_service: registry}, stereotype_instances = [circuit_breaker_link, restful_http], tagged_values = {'Circuit Breaker': 'Hystrix'})
add_links({registry: gateway}, stereotype_instances = [restful_http])
add_links({user: gateway}, stereotype_instances = [restful_http])
add_links({gateway: user}, stereotype_instances = [restful_http])
add_links({gateway: notification_service}, stereotype_instances = [circuit_breaker_link, load_balanced_link, restful_http], tagged_values = {'Load Balancer': 'Ribbon', 'Circuit Breaker': 'Hystrix'})
add_links({gateway: statistics_service}, stereotype_instances = [circuit_breaker_link, load_balanced_link, restful_http], tagged_values = {'Load Balancer': 'Ribbon', 'Circuit Breaker': 'Hystrix'})
add_links({gateway: account_service}, stereotype_instances = [circuit_breaker_link, load_balanced_link, restful_http], tagged_values = {'Load Balancer': 'Ribbon', 'Circuit Breaker': 'Hystrix'})
add_links({gateway: auth_service}, stereotype_instances = [circuit_breaker_link, load_balanced_link, restful_http], tagged_values = {'Load Balancer': 'Ribbon', 'Circuit Breaker': 'Hystrix'})
add_links({auth_service: statistics_service}, stereotype_instances = [authentication_with_plaintext_credentials, plaintext_credentials_link, auth_provider, restful_http], tagged_values = {'Password': 'password\n'})
add_links({auth_service: account_service}, stereotype_instances = [authentication_with_plaintext_credentials, plaintext_credentials_link, auth_provider, restful_http], tagged_values = {'Password': 'password\n'})
add_links({auth_service: notification_service}, stereotype_instances = [authentication_with_plaintext_credentials, plaintext_credentials_link, auth_provider, restful_http], tagged_values = {'Password': 'password\n'})
add_links({turbine_stream_service: monitoring}, stereotype_instances = [restful_http])
add_links({rabbitmq: turbine_stream_service}, stereotype_instances = [restful_http])
add_links({statistics_service: rabbitmq}, stereotype_instances = [restful_http])
add_links({account_service: rabbitmq}, stereotype_instances = [circuit_breaker_link, restful_http], tagged_values = {'Circuit Breaker': 'Hystrix'})
add_links({notification_service: rabbitmq}, stereotype_instances = [restful_http])
add_links({external_website: statistics_service}, stereotype_instances = [restful_http])
add_links({notification_service: mail_server}, stereotype_instances = [plaintext_credentials_link, restful_http])
model = CBundle(model_name, elements = rabbitmq.class_object.get_connected_elements())
def run():
    generator = PlantUMLGenerator()
    generator.plant_uml_jar_path = plantuml_path
    generator.directory = output_directory
    generator.object_model_renderer.left_to_right = True
    generator.generate_object_models(model_name, [model, {}])
    print(f"Generated models in {generator.directory!s}/" + model_name)
if __name__ == "__main__":
    run()